### ISSUE TITLE
Can't find stylesheet to import "/node_modules/ngx-snotifire/styles/"

### ISSUE THREAD

**Issue by MohammedAldosari** [ccpatrut/ngx-snotifire#6]
I'm trying to replace ng-snotify with ngx-snotifire and I have managed to replace every thing but the issue is when trying to replace the styles file from 
`@import "/node_modules/ng-snotify/styles/simple";`
to 
`@import "/node_modules/ngx-snotifire/styles/simple";`

**Comment by ccpatrut** [comment]
Hi,
I managed to find the issue and fixed the problem in 15.0.4.
Could you please have a look on it and let me know? 

PR: https://github.com/ccpatrut/ngx-snotifire/pull/12/files
